version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 19012002
      MYSQL_DATABASE: kp
    ports:
      - "3306:3306"
    volumes:
      - ./kp.sql:/docker-entrypoint-initdb.d/kp.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 19012002
    ports:
      - "8080:80"

volumes:
  db_data:
